### PR TITLE
Spanish translation

### PR DESCRIPTION
**Pull request by phpbb-es**
Spanish translation

### CODE REVIEW

**Comment by phpbb-es** [comment]
Close Arty, already translated. ;)

**Comment by Galixte** [comment]
Where ? I don’t see any ES translation here: https://github.com/cyberalien/sass_compiler/tree/master/arty/scss/language.

**Comment by phpbb-es** [comment]
This...
https://github.com/cyberalien/sass_compiler/pull/3

**Comment by Galixte** [comment]
Thanks. It’s merged ;)

**Pull request closed without merging**
